### ISSUE TITLE
release task list

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofBook#108]
I am making a list here of things I'm spotting that need fixing in the book and from the OF forum post  (http://forum.openframeworks.cc/t/openframeworks-book-review-request/18436).  I will keep editing this issue as I review....

**Overall**

- [ ] root index page needs a design or a redirect (ie, this looks bad! http://openframeworks.cc/ofBook/)
- [x] chapter standardization (capitalization, etc) some chapters also have the word chapter in them, ie "Data Visualization Chapter" -- would be good to remove and standardize
- [ ] javascript for the sidebar doesn't really highlight last section (via clayh)
- [x] tools section should come earlier
- [ ] 2nd half of Roy's chapter should come back (I split it in half to work on it)
- [ ] functions linked to API possible ?  (via clayh)
- [x] rename the "Project Breakdowns" section to "Case Studies." (via clayh)
- [ ] missing:  the use of the power of the hypertext  (needs more links and cross referencing) (via chemabc)
- [ ] explain differences between platforms and IDE's, pros and cons, how to manage dependencies, etc (via chemabc)
- [ ] ofxaddons chapter (addons chapter)  (via amnon)
- [ ] comparison may be suitable with regard to the image options: ofPixels, ofImage, ofTexture, ofFbo. Also clarifying their respective constants with regard to GREYSCALE / RGB / RGBA.  (via amnon)  (could this be in an appendix?)

**Chapters**

- foreward
	- [x] need full list of participants
- Basics 
	- [x] In Basics > Compiling My First App the reader is directed towards ideone. On this site the C++11 language is no longer in the list, only C++14. (via amnon)
- OOPs
	- [x] generally feels like it needs a push with modern practices
- Animation
	- [ ] [note: add screenshot of simple particle examples]
	- [ ] [more: show example]
	- [x] where to go further seems incomplete
- Data vis chapter
	- [x] markdown formatting can be given some love here
	- [ ] has IMAGE HERE
	- [ ] *Vectors? Explain here – or has this happened elsewhere?
	- [ ] code formatting needs help
		- lots of things like ofToInt(split[    0]);
	- [ ] Working with APIs seems unfinished
	- [ ] Further resources seems unfinished
	- [ ] this chapter seems fairly desperate for images
- Memory 
	- [x] In Advanced Topics > Memory in C++ there are many code snippets. Some of them miss a semicolon, which means you get compiler errors, when you copy-paste them to actually try it out in practice. (via amnon)
	- [x] change 4/8 to "A pointer usually occupies 4 or 8 bytes"  (via cabral1349)
	- [ ] graphics can be given a makeover (they are fine as is, but would be good to look at consistency with vector graphics / line weight / fonts) 
- Image processing
	- [x] 3.# section needs completing
- Hardware
	- [ ] I think this image of serial cable is taken from sparkfun, we might want to shoot an image or find one that we have rights for.
- Advanced Graphics
	- [ ] it may be useful to have some kind of quick-view comparison schematic of the different options mentioned on this page: ofPolyline, ofPath, ofMesh, ofVboMesh, and of3dPrimitive. For example when each should be used, unique features/limitations, 2D/3D, CPU/GPU, etc.  (via amnon)
- IOS
	- [ ] suggest to add some information on how to publish to the App Stores (via xavivives)
	- [ ] ending (lifehacks? case studies?) seems kind of unfinished, chapter ends a bit abruptly
- Math
	- [x] CSS work to make the figures more formatted like other images in the book (ie stuff like this needs love http://i.imgur.com/U7YA0zL.png) 
	- [ ] Markdown formatting (chapter structure) seems a little wonky,  H5 tags (this might be the only chapter to have them) are kind of small and overall it feels a little confusing to navigate. 
- Threads
	- [x] graphics can be given a makeover (they are fine as is, but would be good to look at consistency with vector graphics / line weight / fonts) 
- C++ 11
	- [ ] chapter is not finished 
- Case Study : Line Segments Space
	- [x] Chapter still has editing notes in it
	- [ ] chapter is not finished 
	- [ ] graphics can be given a makeover (they are fine as is, but would be good to look at consistency with vector graphics / line weight / fonts) -- author asks for redraw
	- [ ] side by side images can be done via image editing (ie, make one image w/ side by side)
- Case Study: Anthropocene, an body reactive video installation
	- [x] this chapter still feels like needs some editing down to more manageable length
	- [ ] markdown formatting help is needed

**Comment by bakercp** [comment]
Who is in charge of the OOPs chapter?  I could help update it and have a lot of intro-particle system code from my intro courses (https://github.com/bakercp/ExperimentalMedia2014/tree/gh-pages/examples/Week11).

**Comment by ofZach** [comment]
@ruxrux is responsible for the OOOPs chapter, I'm sure help there would be great !!

**Comment by roymacdonald** [comment]
Hey Zach, the second half of my chapter is somehow related to the oops chapter. Sort of an oops conceptual explanation thing. Should we move it into another chapter, put it into the oops chapter or leave it in mine? Did you add anything to it?

it was pointed "explain differences between platforms and IDE's, pros and cons, how to manage dependencies". This is somehow related to my chapter, as I sort of mention some of these there. I can expand it a bit to cover those topics but I feel that it might be  out of scope in the sense that my chapter is about getting OF running, straight and simple.
What do you think?

best

**Comment by roymacdonald** [comment]
@ofZach do you plan to do anything with the second half of my chapter? If yes can you share it with me please? or is there anything I can help with it? Look at my previous post in this issue.
Best!

**Comment by bilderbuchi** [comment]
tbh, I don't really get the title "Ooops! = Object Oriented Programming + Classes". maybe something less...playful... would be appropriate?

**Comment by brannondorsey** [comment]
The Memory chapter still needs a bit of love. One more pass should do it justice. https://github.com/openframeworks/ofBook/pull/55.

**Comment by ruxrux** [comment]
@cristoph happy to change if everyone feels that way but the point is
exactly to be playful == code should be fun!

**Comment by mikewesthad** [comment]
One more thing for the overall list - I think it would be good to have xcode, codeblocks and visual studio project files for each chapter's code (or ofSketch files if applicable).  Project generator from master should be useful for that, no?

**Comment by mikewesthad** [comment]
Yeah I'd agree with that.  I didn't intend it to be suggested as a release blocker.  I haven't been thinking of this list as a collection of release blockers (since we've got a new chapter as one of the items), more as a task list.

**Comment by ofZach** [comment]
I'm closing this issue since we've somewhat released now -- going to focus on a new list with changes to the design / editing, etc.
